name: Style

on:
  push:
  pull_request:

jobs:
  style:
    name: PHP CS-Fixer
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Run Diff Php CS-Fixer
        run: ./vendor/bin/php-cs-fixer --diff --dry-run -v fix .
